// Generated by ./gradlew types.ts
export type Id<T extends Entity<T>> = number & {_of?: T}
export type Entity<T extends Entity<T>> = {id: Id<T>}
export interface UpdatableEntity extends Entity<any> {updatedAt?: Instant}

// class auth.ApiKey
export interface ApiKey {createdAt: Instant; id: Id<ApiKey>; key: string; lastUsedAt?: Instant; name: string; updatedAt?: Instant; userId: Id<User>}
// class auth.EmailCodeRequest
export interface EmailCodeRequest {code: string; email: Email}
// class auth.EmailRequest
export interface EmailRequest {email: Email}
// class db.Id

// class history.Change
export interface Change {changedAt: Instant; changedBy?: Id<User>; new: Record<string, string>; old: Record<string, string>; rowId: Id<any>; table: string}
// class mcp.GetStoryArgs
export interface GetStoryArgs {project_id: number; story_id: number}
// class mcp.InitializeResult
export interface InitializeResult {capabilities: Record<string, any>; protocolVersion: string; serverInfo: ServerInfo}
// class mcp.JsonRpcError
export interface JsonRpcError {code: number; message: string}
// class mcp.JsonRpcRequest
export interface JsonRpcRequest {id?: any; jsonrpc: string; method: string; params: Record<string, any>}
// class mcp.JsonRpcResponse
export interface JsonRpcResponse {error?: JsonRpcError; id?: any; jsonrpc: string; result?: any}
// class mcp.ListStoriesArgs
export interface ListStoriesArgs {project_id: number; q?: string; status?: string; type?: string}
// class mcp.ResourcesListResult
export interface ResourcesListResult {resources: Array<any>}
// class mcp.ServerInfo
export interface ServerInfo {name: string; version: string}
// class mcp.Tool
export interface Tool {description: string; inputSchema: ToolSchema; name: string}
// class mcp.ToolCallResult
export interface ToolCallResult {content: Array<ToolContent>}
// class mcp.ToolContent
export interface ToolContent {text: string; type: string}
// class mcp.ToolDef
export interface ToolDef<T> {description: string; inputClass: KClass<any>; name: string; required: Array<string>}
// class mcp.ToolSchema
export interface ToolSchema {properties: Record<string, any>; required: Array<string>; type: string}
// class mcp.ToolsListResult
export interface ToolsListResult {tools: Array<Tool>}
// class stories.Epic
export interface Epic {comments: Array<StoryComment>; createdAt: Instant; createdBy?: Id<User>; deleted: boolean; description?: string; id: Id<Epic>; isNew?: boolean; name: string; order: number; projectId: Id<Project>; tag: string; updatedAt?: Instant}
// class stories.GitHubAuthor
export interface GitHubAuthor {email?: Email; name?: string}
// class stories.GitHubCommit
export interface GitHubCommit {added?: Array<string>; author?: GitHubAuthor; id: string; message: string; modified?: Array<string>; removed?: Array<string>; timestamp?: string; url?: string}
// class stories.GitHubPushPayload
export interface GitHubPushPayload {commits: Array<GitHubCommit>; compare?: string; ref?: string; repository?: GitHubRepository}
// class stories.GitHubRepository
export interface GitHubRepository {fullName: string}
// class stories.Iteration
export interface Iteration {acceptedPoints?: number; endDate: LocalDate; length: number; number: number; projectId: Id<Project>; startDate: LocalDate; teamStrength: number}
// class stories.Project$Status
export enum ProjectStatus {ACTIVE = 'ACTIVE', DELETED = 'DELETED'}
// class stories.Project
export interface Project {bugsEstimatable: boolean; createdAt: Instant; currentIterationNum: number; defaultStoryPoints?: number; description?: string; id: Id<Project>; iterationWeeks: number; name: string; reviewTypes: Array<string>; startDay: DayOfWeek; status: ProjectStatus; tags: Array<string>; timezone: string; updatedAt?: Instant; velocity: number; velocityAveragedOver: number; webhookSecret: string}
// class stories.ProjectEvents$Update
export interface ProjectEventsUpdate {entity: UpdatableEntity; eventType: string; requesterId: string}
// class stories.ProjectExport
export interface ProjectExport {epics: Array<Epic>; iterations: Array<Iteration>; memberUsers: Array<ProjectMemberUser>; project: Project; stories: Array<Story>}
// class stories.ProjectMember
export interface ProjectMember {commentNotifications: boolean; createdAt: Instant; id: Id<ProjectMember>; lastViewedAt?: Instant; mentionNotifications: boolean; projectId: Id<Project>; role: Role; updatedAt?: Instant; userId: Id<User>}
// class stories.ProjectMemberRequest
export interface ProjectMemberRequest {email: Email; id?: Id<ProjectMember>; initials: string; name: string; role: Role}
// class stories.ProjectMemberUser
export interface ProjectMemberUser {id: Id<ProjectMember>; member: ProjectMember; user: User}
// class stories.Story$Attachment
export interface StoryAttachment {filename: string; height?: number; id?: number; size: number; width?: number}
// class stories.Story$Blocker
export interface StoryBlocker {createdAt: Instant; createdBy: Id<User>; resolvedAt?: Instant; text?: string}
// class stories.Story$Comment
export interface StoryComment {attachments: Array<StoryAttachment>; createdAt: Instant; createdBy?: Id<User>; text?: string; updatedAt: Instant}
// class stories.Story$Review$Status
export enum StoryReviewStatus {UNSTARTED = 'UNSTARTED', IN_REVIEW = 'IN_REVIEW', PASS = 'PASS', REVISE = 'REVISE'}
// class stories.Story$Review
export interface StoryReview {createdAt: Instant; reviewerId?: Id<User>; status: StoryReviewStatus; type: string; updatedAt: Instant}
// class stories.Story$Status
export enum StoryStatus {ACCEPTED = 'ACCEPTED', DELIVERED = 'DELIVERED', FINISHED = 'FINISHED', STARTED = 'STARTED', REJECTED = 'REJECTED', UNSTARTED = 'UNSTARTED', UNSCHEDULED = 'UNSCHEDULED', DELETED = 'DELETED'}
// class stories.Story$Task
export interface StoryTask {completedAt?: Instant; createdAt: Instant; text: string}
// class stories.Story$Type
export enum StoryType {FEATURE = 'FEATURE', BUG = 'BUG', CHORE = 'CHORE', RELEASE = 'RELEASE'}
// class stories.Story
export interface Story {acceptedAt?: Instant; assignedTo?: Id<User>; blockers: Array<StoryBlocker>; comments: Array<StoryComment>; createdAt: Instant; createdBy?: Id<User>; deadline?: LocalDate; description?: string; externalId?: string; id: Id<Story>; isNew?: boolean; iteration?: number; name: string; order: number; points?: number; projectId: Id<Project>; reviews: Array<StoryReview>; status: StoryStatus; tags: Array<string>; tasks: Array<StoryTask>; type: StoryType; updatedAt?: Instant}
// class stories.TeamStrengthRequest
export interface TeamStrengthRequest {teamStrength: number}
// class users.ChangeLangRequest
export interface ChangeLangRequest {lang: string}
// class users.Role
export enum Role {ADMIN = 'ADMIN', OWNER = 'OWNER', MEMBER = 'MEMBER', VIEWER = 'VIEWER'}
// class users.User
export interface User {avatarUrl?: URI; createdAt: Instant; email: Email; firstName: string; id: Id<User>; initials?: string; isAdmin: boolean; lang: string; lastLoginAt?: Instant; lastName: string; name: string; updatedAt?: Instant; username?: string}
// class kotlin.reflect.KClass
export interface KClass<T> {constructors: Array<KFunction<any>>; isAbstract: boolean; isCompanion: boolean; isData: boolean; isFinal: boolean; isFun: boolean; isInner: boolean; isOpen: boolean; isSealed: boolean; isValue: boolean; members: Array<KCallable<any>>; nestedClasses: Array<KClass<any>>; objectInstance?: any; qualifiedName?: string; sealedSubclasses: Array<KClass<any>>; simpleName?: string; supertypes: Array<KType>; typeParameters: Array<KTypeParameter>; visibility?: KVisibility; annotations: Array<Annotation>}
// class klite.jdbc.UpdatableEntity
export interface UpdatableEntity {updatedAt?: Instant}
// class kotlin.reflect.KFunction
export interface KFunction<out R> {isExternal: boolean; isInfix: boolean; isInline: boolean; isOperator: boolean; isSuspend: boolean; annotations: Array<Annotation>; isAbstract: boolean; isFinal: boolean; isOpen: boolean; name: string; parameters: Array<KParameter>; returnType: KType; typeParameters: Array<KTypeParameter>; visibility?: KVisibility}
// class kotlin.reflect.KCallable
export interface KCallable<out R> {isAbstract: boolean; isFinal: boolean; isOpen: boolean; isSuspend: boolean; name: string; parameters: Array<KParameter>; returnType: KType; typeParameters: Array<KTypeParameter>; visibility?: KVisibility; annotations: Array<Annotation>}
// class kotlin.reflect.KType
export interface KType {arguments: Array<KTypeProjection>; classifier?: KClassifier; isMarkedNullable: boolean; annotations: Array<Annotation>}
// class kotlin.reflect.KTypeParameter
export interface KTypeParameter {isReified: boolean; name: string; upperBounds: Array<KType>; variance: KVariance}
// class kotlin.reflect.KVisibility
export enum KVisibility {PUBLIC = 'PUBLIC', PROTECTED = 'PROTECTED', INTERNAL = 'INTERNAL', PRIVATE = 'PRIVATE'}
// class kotlin.reflect.KParameter
export interface KParameter {index: number; isOptional: boolean; isVararg: boolean; kind: KParameterKind; name?: string; type: KType; annotations: Array<Annotation>}
// class kotlin.reflect.KTypeProjection
export interface KTypeProjection {type?: KType; variance?: KVariance}
// class kotlin.reflect.KVariance
export enum KVariance {INVARIANT = 'INVARIANT', IN = 'IN', OUT = 'OUT'}
// class kotlin.reflect.KParameter$Kind
export enum KParameterKind {INSTANCE = 'INSTANCE', CONTEXT = 'CONTEXT', EXTENSION_RECEIVER = 'EXTENSION_RECEIVER', VALUE = 'VALUE'}

// java.time.LocalDate
export type LocalDate = `${number}-${number}-${number}`
// java.time.Instant
export type Instant = `${number}-${number}-${number}T${number}:${number}:${number}Z`
// java.net.URI
export type URI = `${string}://${string}`
// klite.Email
export type Email = `${string}@${string}`
// class java.time.DayOfWeek
export enum DayOfWeek {MONDAY = 'MONDAY', TUESDAY = 'TUESDAY', WEDNESDAY = 'WEDNESDAY', THURSDAY = 'THURSDAY', FRIDAY = 'FRIDAY', SATURDAY = 'SATURDAY', SUNDAY = 'SUNDAY'}

// db.TestData
export const admin = {"createdAt":"2025-03-03T00:00:00Z","email":"admin@azib.net","firstName":"Test","id":200000001,"isAdmin":true,"lang":"en","lastName":"Admin","name":"Test Admin"} as User
export const apiKey = {"createdAt":"2025-03-03T00:00:00Z","id":200000007,"key":"sk-st-test-key","name":"MCP","userId":200000002} as ApiKey
export const change = {"changedAt":"2025-03-03T00:00:00Z","changedBy":200000002,"new":{"status":"DONE"},"old":{"status":"TODO"},"rowId":200000004,"table":"stories"} as Change
export const date = "2025-03-03" as LocalDate
export const epic = {"comments":[],"createdAt":"2025-03-03T00:00:00Z","deleted":false,"id":200000003,"name":"Epic 1","order":0.0,"projectId":1,"tag":"epic1"} as Epic
export const iteration = {"endDate":"2025-03-10","length":1,"number":1,"projectId":1,"startDate":"2025-03-03","teamStrength":100} as Iteration
export const now = "2025-03-03T00:00:00Z" as Instant
export const project = {"bugsEstimatable":false,"createdAt":"2025-03-03T00:00:00Z","currentIterationNum":1,"defaultStoryPoints":1,"description":"Description","id":1,"iterationWeeks":1,"name":"Project 1","reviewTypes":["Test (QA)","Design","Code","Security"],"startDay":"MONDAY","status":"ACTIVE","tags":[],"timezone":"UTC","velocity":10,"velocityAveragedOver":3,"webhookSecret":"73bfc75b-d0f4-43f8-9bd2-378a56291476"} as Project
export const projectMember = {"commentNotifications":false,"createdAt":"2025-03-03T00:00:00Z","id":200000006,"mentionNotifications":false,"projectId":1,"role":"MEMBER","userId":200000002} as ProjectMember
export const projectMemberUser = {"id":200000006,"member":{"commentNotifications":false,"createdAt":"2025-03-03T00:00:00Z","id":200000006,"mentionNotifications":false,"projectId":1,"role":"MEMBER","userId":200000002},"user":{"createdAt":"2025-03-03T00:00:00Z","email":"user@azib.net","firstName":"Test","id":200000002,"isAdmin":false,"lang":"en","lastName":"User","name":"Test User"}} as ProjectMemberUser
export const story = {"blockers":[],"comments":[],"createdAt":"2025-03-03T00:00:00Z","id":200000004,"name":"Story 1","order":0.0,"projectId":1,"reviews":[],"status":"UNSTARTED","tags":[],"tasks":[],"type":"FEATURE"} as Story
export const story2 = {"blockers":[],"comments":[],"createdAt":"2025-03-03T00:00:00Z","id":200000005,"name":"Story 2","order":2.0,"projectId":1,"reviews":[],"status":"UNSTARTED","tags":[],"tasks":[],"type":"FEATURE"} as Story
export const user = {"createdAt":"2025-03-03T00:00:00Z","email":"user@azib.net","firstName":"Test","id":200000002,"isAdmin":false,"lang":"en","lastName":"User","name":"Test User"} as User
