// Generated by ./gradlew types.ts
// TODO export type Id<T extends Entity<T>> = number & {_of?: T}
export type Entity<T extends Entity<T>> = {id: Id<T>}

// class auth.EmailCodeRequest
export interface EmailCodeRequest {code: string; email: Email}
// class auth.EmailRequest
export interface EmailRequest {email: Email}
// class db.Id
export type Id<T> = number
// class stories.Epic
export interface Epic {comments: Array<StoryComment>; createdAt: Instant; createdBy?: Id<User>; description?: string; id: Id<Epic>; name: string; projectId: Id<Project>; tag: string; updatedAt?: Instant}
// class stories.Iteration
export interface Iteration {acceptedPoints?: number; endDate: LocalDate; length: number; number: number; projectId: Id<Project>; startDate: LocalDate; teamStrength: number}
// class stories.Project
export interface Project {bugsEstimatable: boolean; createdAt: Instant; currentIterationNum: number; defaultStoryPoints?: number; description?: string; id: Id<Project>; iterationWeeks: number; name: string; reviewTypes: Array<string>; startDay: DayOfWeek; tags: Array<string>; timezone: string; updatedAt?: Instant; velocity: number; velocityAveragedOver: number}
// class stories.ProjectMember
export interface ProjectMember {commentNotifications: boolean; createdAt: Instant; id: Id<ProjectMember>; lastViewedAt?: Instant; mentionNotifications: boolean; projectId: Id<Project>; role: Role; updatedAt?: Instant; userId: Id<User>}
// class stories.ProjectMemberRequest
export interface ProjectMemberRequest {email: Email; initials: string; name: string; role: Role}
// class stories.ProjectMemberUser
export interface ProjectMemberUser {id: Id<ProjectMember>; member: ProjectMember; user: User}
// class stories.Story$Attachment
export interface StoryAttachment {filename: string; height?: number; id?: number; size: number; width?: number}
// class stories.Story$Blocker
export interface StoryBlocker {createdAt: Instant; createdBy: Id<User>; resolvedAt?: Instant; text?: string}
// class stories.Story$Comment
export interface StoryComment {attachments: Array<StoryAttachment>; createdAt: Instant; createdBy: Id<User>; text?: string; updatedAt: Instant}
// class stories.Story$Review$Status
export enum StoryReviewStatus {UNSTARTED = 'UNSTARTED', IN_REVIEW = 'IN_REVIEW', PASS = 'PASS', REVISE = 'REVISE'}
// class stories.Story$Review
export interface StoryReview {createdAt: Instant; reviewerId?: Id<User>; status: StoryReviewStatus; type: string; updatedAt: Instant}
// class stories.Story$Status
export enum StoryStatus {ACCEPTED = 'ACCEPTED', DELIVERED = 'DELIVERED', FINISHED = 'FINISHED', STARTED = 'STARTED', REJECTED = 'REJECTED', PLANNED = 'PLANNED', UNSTARTED = 'UNSTARTED', UNSCHEDULED = 'UNSCHEDULED', DELETED = 'DELETED'}
// class stories.Story$Task
export interface StoryTask {completedAt?: Instant; createdAt: Instant; text: string}
// class stories.Story$Type
export enum StoryType {FEATURE = 'FEATURE', BUG = 'BUG', CHORE = 'CHORE', RELEASE = 'RELEASE'}
// class stories.Story
export interface Story {acceptedAt?: Instant; assignedTo?: Id<User>; blockers: Array<StoryBlocker>; comments: Array<StoryComment>; createdAt: Instant; createdBy?: Id<User>; deadline?: LocalDate; description?: string; externalId?: string; id: Id<Story>; iteration?: number; name: string; order: number; points?: number; projectId: Id<Project>; reviews: Array<StoryReview>; status: StoryStatus; tags: Array<string>; tasks: Array<StoryTask>; type: StoryType; updatedAt?: Instant}
// class users.ChangeLangRequest
export interface ChangeLangRequest {lang: string}
// class users.Role
export enum Role {ADMIN = 'ADMIN', OWNER = 'OWNER', MEMBER = 'MEMBER', VIEWER = 'VIEWER'}
// class users.User
export interface User {avatarUrl?: URI; createdAt: Instant; email: Email; firstName: string; id: Id<User>; initials?: string; lang: string; lastLoginAt?: Instant; lastName: string; name: string; role: Role; updatedAt?: Instant; username?: string}

// java.time.LocalDate
export type LocalDate = `${number}-${number}-${number}`
// java.time.Instant
export type Instant = `${number}-${number}-${number}T${number}:${number}:${number}Z`
// java.net.URI
export type URI = `${string}://${string}`
// klite.Email
export type Email = `${string}@${string}`
// class java.time.DayOfWeek
export enum DayOfWeek {MONDAY = 'MONDAY', TUESDAY = 'TUESDAY', WEDNESDAY = 'WEDNESDAY', THURSDAY = 'THURSDAY', FRIDAY = 'FRIDAY', SATURDAY = 'SATURDAY', SUNDAY = 'SUNDAY'}

// db.TestData
export const date = "2025-03-03" as LocalDate
export const now = "2025-03-03T00:00:00Z" as Instant
export const project = {"bugsEstimatable":false,"createdAt":"2025-03-03T00:00:00Z","currentIterationNum":1,"defaultStoryPoints":1,"description":"Description","id":1,"iterationWeeks":1,"name":"Project 1","reviewTypes":["Test (QA)","Design","Code","Security"],"startDay":"MONDAY","tags":[],"timezone":"UTC","velocity":10,"velocityAveragedOver":3} as Project
export const story = {"blockers":[],"comments":[],"createdAt":"2025-03-03T00:00:00Z","id":200000003,"name":"Story 1","order":0.0,"projectId":1,"reviews":[],"status":"UNSTARTED","tags":[],"tasks":[],"type":"FEATURE"} as Story
export const story2 = {"blockers":[],"comments":[],"createdAt":"2025-03-03T00:00:00Z","id":200000004,"name":"Story 2","order":2.0,"projectId":1,"reviews":[],"status":"UNSTARTED","tags":[],"tasks":[],"type":"FEATURE"} as Story
export const user = {"createdAt":"2025-03-03T00:00:00Z","email":"pivotal@codeborne.com","firstName":"Test","id":200000001,"lang":"en","lastName":"Admin","name":"Test Admin","role":"ADMIN"} as User
export const viewer = {"createdAt":"2025-03-03T00:00:00Z","email":"viewer@codeborne.com","firstName":"Test","id":200000002,"lang":"en","lastName":"Viewer","name":"Test Viewer","role":"VIEWER"} as User
