# For deployment
services:
  tracker:
    volumes:
      - /var/tracker/attachments:/app/attachments
    environment:
      - ENV=prod
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - MAIL_FROM
      - SESSION_SECRET
      - OWN_DOMAIN
      - GOOGLE_OAUTH_CLIENT_ID
      - GOOGLE_OAUTH_CLIENT_SECRET
    networks:
      - proxy
      - default
    labels:
      - caddy=${OWN_HOST}
      - caddy.reverse_proxy={{upstreams 8080}}
      - caddy.reverse_proxy.lb_retries=5
      - caddy.reverse_proxy.lb_try_interval=500ms

  db:
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

networks:
  proxy:
    external: true
