# For deployment
services:
  tracker:
    volumes:
      - /var/tracker/attachments:/app/attachments
    environment:
      - ENV=prod
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - MAIL_FROM=storytracker@azib.net
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - proxy
      - default
    labels:
      - caddy=storytracker.azib.net
      - caddy.reverse_proxy={{upstreams 8080}}
      - caddy.reverse_proxy.lb_retries=5
      - caddy.reverse_proxy.lb_try_interval=500ms

  db:
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

networks:
  proxy:
    external: true
