--substitute id=id bigint primary key
--substitute createdBy=createdBy bigint default get_app_user()

--include app_user.sql
--include change_history.sql
--include users.sql
--include courses.sql
--include enrollments.sql
--include course_sessions.sql
--include course_attendances.sql
--include invoices.sql
--include teacher_feedbacks.sql
